import {
  SCARD_SHARE_EXCLUSIVE,
  SCARD_SHARE_SHARED,
  SCARD_SHARE_DIRECT,
  SCARD_PROTOCOL_T0,
  SCARD_PROTOCOL_T1,
  SCARD_PROTOCOL_RAW,
  SCARD_PROTOCOL_UNDEFINED,
  SCARD_LEAVE_CARD,
  SCARD_RESET_CARD,
  SCARD_UNPOWER_CARD,
  SCARD_EJECT_CARD,
  SCARD_STATE_UNAWARE,
  SCARD_STATE_IGNORE,
  SCARD_STATE_CHANGED,
  SCARD_STATE_UNKNOWN,
  SCARD_STATE_UNAVAILABLE,
  SCARD_STATE_EMPTY,
  SCARD_STATE_PRESENT,
  SCARD_STATE_ATRMATCH,
  SCARD_STATE_EXCLUSIVE,
  SCARD_STATE_INUSE,
  SCARD_STATE_MUTE,
} from "./native.js";

const ShareMode = Object.freeze({
  EXCLUSIVE: SCARD_SHARE_EXCLUSIVE,
  SHARED: SCARD_SHARE_SHARED,
  DIRECT: SCARD_SHARE_DIRECT,
});

const Protocol = Object.freeze({
  T0: SCARD_PROTOCOL_T0,
  T1: SCARD_PROTOCOL_T1,
  RAW: SCARD_PROTOCOL_RAW,
  UNDEFINED: SCARD_PROTOCOL_UNDEFINED,
});

const Disposition = Object.freeze({
  LEAVE: SCARD_LEAVE_CARD,
  RESET: SCARD_RESET_CARD,
  UNPOWER: SCARD_UNPOWER_CARD,
  EJECT: SCARD_EJECT_CARD,
});

const State = Object.freeze({
  UNAWARE: SCARD_STATE_UNAWARE,
  IGNORE: SCARD_STATE_IGNORE,
  CHANGED: SCARD_STATE_CHANGED,
  UNKNOWN: SCARD_STATE_UNKNOWN,
  UNAVAILABLE: SCARD_STATE_UNAVAILABLE,
  EMPTY: SCARD_STATE_EMPTY,
  PRESENT: SCARD_STATE_PRESENT,
  ATRMATCH: SCARD_STATE_ATRMATCH,
  EXCLUSIVE: SCARD_STATE_EXCLUSIVE,
  INUSE: SCARD_STATE_INUSE,
  MUTE: SCARD_STATE_MUTE,
});

export { ShareMode, Protocol, Disposition, State };
